name: RPM Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: fedora-latest
    steps:
    - uses: actions/checkout@v2


    - name: Prepare environment
      run: |
        sudo dnf install -y rpmdevtools rpmlint
        rpmdev-setuptree
        workdir="$(pwd)/rpm_workdir"
        pwd
        cp libldacdec.spec ~/.rpmbuild/SPECS/libldacdec.spec
        cp ldacBT-dec.pc ~/.rpmbuild/SOURCES/libldacdec.spec
        spectool -g -R ~/.rpmbuild/SPECS/libldacdec.spec
        rpmbuild -ba ~/.rpmbuild/SPECS/libldacdec.spec
        cp  ~/.rpmbuild/SRPMS/* $workdir
        cp ~/.rpmbuild/RPMS/* $workdir
        
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Binary RPM
        path: $workdir
